### ISSUE TITLE
Please use org.scalamacros paradise

### ISSUE THREAD

**Issue by olafurpg** [pcejrowski/safe-builder#4]
Hey! Heads up, the artifact for "macro paradise" (https://docs.scala-lang.org/overviews/macros/paradise.html) is org.scalamacros:paradise, not org.scalameta paradise. Development on Scalameta macro annotations stopped over 1 year ago, the repository is archived on GitHub and there will be no release for 2.13. On the other hand, org.scalamacros paradise macro annotations have been merged into the Scala compiler so there will no longer be a need for a compiler plugin in 2.13.

Slinky migrated to org.scalamacros:paradise from org.scalameta:paradise and reported "drastically improved error messages" https://medium.com/@shadaj/introducing-slinky-0-5-0-21deb2546d65#0692

**Comment by pcejrowski** [comment]
Many thanks for those information, @olafurpg!
